language: cpp

matrix:
  include:

    # macOS
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'

    # linux
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6','libxcb-util0-dev', 'libxcb-xkb-dev', 'libgtkmm-3.0-dev']
      env: COMPILER='g++-6' BUILD_TYPE='Debug'

install:
  true
  
script:
  - mkdir -p build
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        cmake -GXcode ../vstgui/
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        cmake ../vstgui/
    fi
  - cmake --build .

