version: 1.0.0.{build}
os:
- Windows Server 2016
environment:
  BUILD_TYPE: Release
  ARCH: Win64
  matrix:
  - GENERATOR: Visual Studio 15 2017 %ARCH%
build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    cmake -H. -Bbuild -G"%GENERATOR%"

    cmake --build build --config %BUILD_TYPE%
