name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cmake@v1
      with:
        source-dir: '${{github.workspace}}/vstgui'
        build-dir: '${{github.workspace}}/build'
        build-type: 'Debug'
        build-vstgui-standalone: OFF
